Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -32,16 +32,16 @@ steps:
       exit 1
       fi
      
-      - task: Bash@3
-        displayName: 'Check PGP URL status'
-        inputs:
-          targetType: 'inline'
-          script: |
-           #!/bin/bash
+- task: Bash@3
+  displayName: 'Check PGP URL status'
+  inputs:
+    targetType: 'inline'
+    script: |
+      #!/bin/bash
         
-        if curl -s --head  --request GET https://www.pocketgeekprivacy.com | grep "200 OK" > /dev/null;
-        then echo "The HTTP server on www.pocketgeekprivacy.com and pocketgeekprivacy.com is UP!" #> /dev/null
+      if curl -s --head  --request GET https://www.pocketgeekprivacy.com | grep "200 OK" > /dev/null;
+      then echo "The HTTP server on www.pocketgeekprivacy.com and pocketgeekprivacy.com is UP!" #> /dev/null
         
-        else echo  "##vso[task.logissue type=error]The HTTP server on www.pocketgeekprivacy.com OR pocketgeekprivacy.com is DOWN"
-        exit 1
-        fi
+      else echo  "##vso[task.logissue type=error]The HTTP server on www.pocketgeekprivacy.com OR pocketgeekprivacy.com is DOWN"
+      exit 1
+      fi
