Update azure-pipelines.yml for Azure Pipelines
Added check for PGP url status

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -17,10 +17,8 @@ pool:
   vmImage: ubuntu-latest
 
 steps:
-- script: echo Hello, world!
-  displayName: 'Run a one-line script'
-
 - task: Bash@3
+  displayName: 'Check PGID URL status'
   inputs:
     targetType: 'inline'
     script: |
@@ -28,9 +26,22 @@ steps:
       DATENOW=`date +%Y%m%d-%H%M%S`
       
       if curl -s --head  --request GET https://www.pocketgeekid.com | grep "200 OK" > /dev/null && curl -s --head --request GET https://pocketgeekid.com | grep "200 OK" > /dev/null;
-      
       then echo "The HTTP server on www.pocketgeekid.com and pocketgeekid.com is UP!" #> /dev/null
       
       else echo  "##vso[task.logissue type=error]The HTTP server on www.pocketgeekid.com OR pocketgeekid.com was DOWN at $DATENOW"
       exit 1
       fi
+     
+      - task: Bash@3
+        displayName: 'Check PGP URL status'
+        inputs:
+          targetType: 'inline'
+          script: |
+           #!/bin/bash
+        
+        if curl -s --head  --request GET https://www.pocketgeekprivacy.com | grep "200 OK" > /dev/null;
+        then echo "The HTTP server on www.pocketgeekprivacy.com and pocketgeekprivacy.com is UP!" #> /dev/null
+        
+        else echo  "##vso[task.logissue type=error]The HTTP server on www.pocketgeekprivacy.com OR pocketgeekprivacy.com is DOWN"
+        exit 1
+        fi
